/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.publicom2.vue;

import com.publicom2.controller.AddViewController;
import java.util.logging.Level;
import java.util.logging.Logger;
import publicom2.model.Utilisateur;
import publicom2.model.UtilisateurDAO;

/**
 *
 * @author r.delmas
 */
public class AddView extends javax.swing.JFrame {

    //Controlleur de cette vue
    private AddViewController controller;

    //Constructeur
    public AddView() {
        //Initialise les composants de la vue
        initComponents();
        //Instance du controlleur
        this.controller = new AddViewController(this);
    }
//ajout methodes getter

    //Retourne le nom du nouvel utilisateur
    private String getNom() {
        return this.WriteNom.getText();
    }

    //Retourne le prenom du nouvel utilisateur
    private String getPrenom() {
        return this.WritePrenom.getText();
    }

    //Retourne le mot de passe du nouvel utilisateur
    private String getMdp() {
        return this.WriteMdp.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDemande = new javax.swing.JLabel();
        txtNom = new javax.swing.JLabel();
        txtPrenom = new javax.swing.JLabel();
        txtMdp = new javax.swing.JLabel();
        WriteNom = new javax.swing.JTextField();
        WritePrenom = new javax.swing.JTextField();
        WriteMdp = new javax.swing.JTextField();
        btnValider = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add User");
        setResizable(false);

        txtDemande.setFont(new java.awt.Font("Dialog", 3, 20)); // NOI18N
        txtDemande.setText("Veuillez renseigner les informations suivantes.");

        txtNom.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtNom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNom.setText("Nom :");

        txtPrenom.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtPrenom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPrenom.setText("Prénom :");

        txtMdp.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtMdp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMdp.setText("Mot de passe :");

        WriteNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WriteNomActionPerformed(evt);
            }
        });

        WritePrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WritePrenomActionPerformed(evt);
            }
        });

        WriteMdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WriteMdpActionPerformed(evt);
            }
        });

        btnValider.setText("Valider");
        btnValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValiderActionPerformed(evt);
            }
        });

        btnReturn.setText("Retour");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnValider, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtDemande))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMdp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WritePrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WriteNom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WriteMdp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnReturn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDemande)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNom)
                    .addComponent(WriteNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrenom)
                    .addComponent(WritePrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMdp)
                    .addComponent(WriteMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(btnValider, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnReturn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void WriteNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WriteNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WriteNomActionPerformed

    private void WritePrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WritePrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WritePrenomActionPerformed

    private void WriteMdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WriteMdpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WriteMdpActionPerformed

    private void btnValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValiderActionPerformed
        //on récupère le nom saisi par l'utilisateur
        String name = this.getNom();
        //Récupère le prenom du nouvel utilisateur
        String firstName = this.getPrenom();
        //Créer l'identifiant du nouvel utilisateur sous le format : nom.prenom
        String username = firstName + "." + name;
        //Récupère le mot de passe du nouvel utilisateur
        String password = this.getMdp();
        //Création d'un objet Utilisateur représentant le nouvel utilisateur
        //Avec le nouvel identifiant, nom, prenom et mot de passe
        Utilisateur user = new Utilisateur(username, password, name, firstName);
        
        AddViewController controller = new AddViewController(this);

        try {
            controller.addUser(user);
        } catch (Exception ex) {
            Logger.getLogger(AddView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnValiderActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        try {
            this.controller.backToMainView();
        } catch (Exception ex) {
            Logger.getLogger(AddView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddView().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField WriteMdp;
    private javax.swing.JTextField WriteNom;
    private javax.swing.JTextField WritePrenom;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnValider;
    private javax.swing.JLabel txtDemande;
    private javax.swing.JLabel txtMdp;
    private javax.swing.JLabel txtNom;
    private javax.swing.JLabel txtPrenom;
    // End of variables declaration//GEN-END:variables
}
