/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.publicom2.vue;

import com.publicom2.controller.AddViewController;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import publicom2.model.Utilisateur;
import publicom2.model.UtilisateurDAO;

/**
 *
 * @author r.delmas
 */
public class AddView extends javax.swing.JFrame {

    //Controlleur de cette vue
    private AddViewController controller;

    //Constructeur
    public AddView() {
        //Initialise les composants de la vue
        initComponents();
        //Instance du controlleur
        this.controller = new AddViewController(this);
        //Ajoute des listeners aux champs de saisie Nom et Prenom pour actualiser le label identifiant
        this.addListenerTextChangeTextFieldNomAndPrenom();
        
        this.getContentPane().setBackground(new Color(205,133,63));
    }
//ajout methodes getter

    //Retourne le nom du nouvel utilisateur
    private String getNom() {
        return this.writeNom.getText();
    }

    //Retourne le prenom du nouvel utilisateur
    private String getPrenom() {
        return this.writePrenom.getText();
    }

    //Retourne le mot de passe du nouvel utilisateur
    private String getMdp() {
        return String.valueOf(this.writeMdp.getPassword());
    }
    
//Setter
    public void setTxtStateAddUser(String textStateAddUser){
        this.txtStateAddUser.setText(textStateAddUser);
}
    
    private void updateTxtIdentifier(){
        this.txtIdentifier.setText("Identifiant : " + this.getNom() + "." + this.getPrenom());
    }
    
    private void addListenerTextChangeTextFieldNomAndPrenom(){
            this.writeNom.getDocument().addDocumentListener(new DocumentListener()
        {
            public void changedUpdate(DocumentEvent e){
                updateTxtIdentifier();
            }
            
            public void removeUpdate(DocumentEvent e){
                this.changedUpdate(e);
            }
                        
            public void insertUpdate(DocumentEvent e){
                this.changedUpdate(e);
            }
        });
        
        this.writePrenom.getDocument().addDocumentListener(new DocumentListener()
        {
            public void changedUpdate(DocumentEvent e){
                updateTxtIdentifier();
            }
            
            public void removeUpdate(DocumentEvent e){
                this.changedUpdate(e);
            }
                        
            public void insertUpdate(DocumentEvent e){
                this.changedUpdate(e);
            }
        });
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDemande = new javax.swing.JLabel();
        txtNom = new javax.swing.JLabel();
        txtPrenom = new javax.swing.JLabel();
        txtMdp = new javax.swing.JLabel();
        writeNom = new javax.swing.JTextField();
        writePrenom = new javax.swing.JTextField();
        btnValider = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        writeMdp = new javax.swing.JPasswordField();
        txtStateAddUser = new javax.swing.JLabel();
        txtIdentifier = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add User");
        setResizable(false);

        txtDemande.setFont(new java.awt.Font("Dialog", 3, 20)); // NOI18N
        txtDemande.setText("Veuillez renseigner les informations suivantes.");

        txtNom.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtNom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNom.setText("Nom :");

        txtPrenom.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtPrenom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPrenom.setText("Prénom :");

        txtMdp.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        txtMdp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMdp.setText("Mot de passe :");

        writePrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writePrenomActionPerformed(evt);
            }
        });

        btnValider.setText("Valider");
        btnValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValiderActionPerformed(evt);
            }
        });

        btnReturn.setText("Retour");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        writeMdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writeMdpActionPerformed(evt);
            }
        });

        txtStateAddUser.setForeground(new java.awt.Color(255, 0, 51));
        txtStateAddUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtIdentifier.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtIdentifier.setText("Identifiant : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnValider, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDemande)
                            .addComponent(btnReturn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(txtStateAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdentifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMdp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(writePrenom, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(writeNom, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(writeMdp))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDemande)
                .addGap(42, 42, 42)
                .addComponent(txtIdentifier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNom)
                    .addComponent(writeNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrenom)
                    .addComponent(writePrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMdp)
                    .addComponent(writeMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtStateAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnValider, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnReturn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void writePrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_writePrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_writePrenomActionPerformed

    private void btnValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValiderActionPerformed
        //on récupère le nom saisi par l'utilisateur
        String name = this.getNom();
        //Récupère le prenom du nouvel utilisateur
        String firstName = this.getPrenom();
        //Créer l'identifiant du nouvel utilisateur sous le format : nom.prenom
        String username = firstName + "." + name;
        //Récupère le mot de passe du nouvel utilisateur
        String password = this.getMdp();
        //Création d'un objet Utilisateur représentant le nouvel utilisateur
        //Avec le nouvel identifiant, nom, prenom et mot de passe
        Utilisateur user = new Utilisateur(username, password, name, firstName);
        //Instance du controlleur
        AddViewController controller = new AddViewController(this);
        //Demande au controlleur d'ajouter l'utilisateur
        try {
            controller.addUser(user);
        } catch (Exception ex) {
            Logger.getLogger(AddView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnValiderActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        //Demande au controlleur de revenir à la vue mainVue
        try {
            this.controller.backToMainView();
        } catch (Exception ex) {
            Logger.getLogger(AddView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnReturnActionPerformed

    private void writeMdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_writeMdpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_writeMdpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddView().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnValider;
    private javax.swing.JLabel txtDemande;
    private javax.swing.JLabel txtIdentifier;
    private javax.swing.JLabel txtMdp;
    private javax.swing.JLabel txtNom;
    private javax.swing.JLabel txtPrenom;
    private javax.swing.JLabel txtStateAddUser;
    private javax.swing.JPasswordField writeMdp;
    private javax.swing.JTextField writeNom;
    private javax.swing.JTextField writePrenom;
    // End of variables declaration//GEN-END:variables
}
